spring.application.name=sistema-ingressos

spring.data.mongodb.uri=mongodb+srv://luiza_helena:safira73eclipse29@sistemaingressos.3bto3wb.mongodb.net/?appName=SistemaIngressos
spring.data.mongodb.database=ingressos

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Server
server.port=8080
